### PR TITLE
add support for provided configuration in Maven plugin

### PR DESCRIPTION
**Pull request by fs111**
We are still using the classic way of installing and uploading jars for all our projects, but we wanted to adopt this plugin instead of the propdeps plugin, which gave us a lot of problems. 

This little change will make sure the provided deps show up in the poms when using gradle install or gradle uploadArchives.

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for the pull request. Would mind also adding support for the OptionalPlugin?

**Comment by fs111** [comment]
I tried, but I don't really understand the mechanics of that part of gradle + we do not use it currently.

**Comment by bmuschko** [comment]
As a side note: optional is actually a Maven concept.

**Comment by bmuschko** [comment]
Could you please also add some tests?

**Comment by fs111** [comment]
I just added a passing test.

**Comment by fs111** [comment]
any chance of getting this merged?

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged. Before we are going to release a new version, we'll still have to add the support for the optional in combination with the Maven plugin. Stay tuned.

**Comment by fs111** [comment]
Thanks for merging!

**Comment by bmuschko** [comment]
@fs111 FYI: We released a new version that includes your pull request.

**Comment by fs111** [comment]
Great! Thanks for the heads-up!

**Pull request merged**
